#!/usr/bin/env perl

# Copyright © 2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

no lib '.';  # CVE-2016-1238

use strict;
use warnings;

use English qw(-no_match_vars);

my $outfile;
for my $i (0..$#ARGV) {
	if ($ARGV[$i] eq '-o') {
		$outfile = $ARGV[$i + 1];
	}
}

my @argv;
my $one_second = 1E6;
my $sset = '/^open';
if (defined $outfile) {
	push @argv, qw(strace -o /dev/null -f), '-e', "trace=$sset", '-e', "inject=$sset:delay_exit=$one_second", '-P', $outfile;
}
push @argv, ('cc', @ARGV);

exec @argv;

# vim:ts=4 sts=4 sw=4 et
